/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cars */
        get: operations["list_cars_api_cars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cars/{car_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Car */
        delete: operations["delete_car_api_cars__car_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cars/{car_id}/aggregate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Car Aggregate */
        get: operations["car_aggregate_api_cars__car_id__aggregate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cars/{car_id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Car Sessions */
        delete: operations["delete_car_sessions_api_cars__car_id__sessions_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cars/{ordinal}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rename Car By Ordinal
         * @description Crowdsourcing path for car names.
         *
         *     The bundled ordinal → name table is community-maintained and will
         *     always lag behind Playground's car-pack drops. When a user sees a
         *     car named `Car #{ordinal}` they can submit the correct name; we
         *     stamp every Car row sharing that ordinal so all tunes of the same
         *     car get fixed at once. The DB row wins over the static lookup for
         *     subsequent reads (PgCarRepository.upsert no longer overwrites
         *     display_name on update).
         */
        patch: operations["rename_car_by_ordinal_api_cars__ordinal__patch"];
        trace?: never;
    };
    "/api/coach/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask
         * @description T112: stream the AskCoach output as chunked transfer-encoded.
         */
        post: operations["ask_api_coach_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Insights */
        get: operations["list_insights_api_coach_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/insights/{insight_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss Insight */
        post: operations["dismiss_insight_api_coach_insights__insight_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/insights/{insight_id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replay Insight
         * @description T115/T116: build a `Replay(kind=telemetry_clip)` from the insight's
         *     cited window.
         */
        post: operations["replay_insight_api_coach_insights__insight_id__replay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/insights/{session_id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate For Session */
        post: operations["generate_for_session_api_coach_insights__session_id__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Coach Status
         * @description API spec §7 + Clarification Q3 `/api/coach/status`.
         */
        get: operations["coach_status_api_coach_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete All Data
         * @description `DELETE /api/data/all` (API spec §13). Gated by header X-Confirm.
         *
         *     Wipes every car (and via FK cascade every session, frame, and
         *     mistake) so the cars dropdown is truly empty afterwards.
         */
        delete: operations["delete_all_data_api_data_all_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/driver/evolution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evolution */
        get: operations["evolution_api_driver_evolution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/driver/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile */
        get: operations["profile_api_driver_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/layouts/{page_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Layout */
        get: operations["get_layout_api_layouts__page_id__get"];
        /** Put Layout */
        put: operations["put_layout_api_layouts__page_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Layout */
        patch: operations["patch_layout_api_layouts__page_id__patch"];
        trace?: never;
    };
    "/api/predict/bestAchievableLap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Best Achievable Lap */
        get: operations["best_achievable_lap_api_predict_bestAchievableLap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predict/crashRisk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Crash Risk */
        get: operations["crash_risk_api_predict_crashRisk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predict/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Finish */
        get: operations["finish_api_predict_finish_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predict/lap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lap
         * @description Project the next ``n`` lap times (api-contract §6).
         *
         *     - Seeds the LapResidualModel from ``Session.best_lap_s`` (replicated up
         *       to ``SEED_WINDOW_LEN`` times by ``lap_count``) and rolls the window
         *       forward across each projection so later laps condition on earlier ones.
         *     - Confidence is monotone non-increasing across ``k``: the raw model
         *       confidence is capped at the first projection's value (the model's raw
         *       confidence can rise as the seed window fills, so without a cap the
         *       net confidence is not strictly monotone), then multiplied by
         *       ``CONFIDENCE_DECAY_PER_LAP ** k``.
         *     - ``predictedAt`` reads ``raceTimeS`` from the most recent hot-cache
         *       frame for this (session, car). When no frame has arrived yet we fall
         *       back to ``0.0`` — callers should treat 0.0 as "no live frame yet".
         *     - ``limiter`` is ``None`` for now; tire-wear gating is a follow-up
         *       (backend work item 1).
         */
        get: operations["lap_api_predict_lap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predict/shift": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Shift Prediction
         * @description FR-021: current shift recommendation for the session's fingerprint.
         */
        get: operations["get_shift_prediction_api_predict_shift_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predict/shift/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Shift Report
         * @description FR-022 / FR-051: per-session shift report aggregated from shift_events_clean.
         */
        get: operations["get_shift_report_api_predict_shift_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predict/shift/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Shift Reset
         * @description FR-023: drop in-memory + on-disk state for a fingerprint.
         */
        post: operations["post_shift_reset_api_predict_shift_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predict/tireFailure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tire Failure */
        get: operations["tire_failure_api_predict_tireFailure_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predict/whatIf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** What If */
        post: operations["what_if_api_predict_whatIf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay/{replay_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Replay */
        get: operations["get_replay_api_replay__replay_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        post?: never;
        /** Delete All Sessions */
        delete: operations["delete_all_sessions_api_sessions_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current Session
         * @description Return the most recent in-flight session (ended_at IS NULL).
         *
         *     The live UI polls this to find the session id to wire predictions,
         *     coach feed, and session detail against. 404 when nothing is open.
         */
        get: operations["current_session_api_sessions_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Detail */
        get: operations["session_detail_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_sessions__session_id__delete"];
        options?: never;
        head?: never;
        /** Patch Session */
        patch: operations["patch_session_api_sessions__session_id__patch"];
        trace?: never;
    };
    "/api/sessions/{session_id}/driver-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Driver Profile */
        get: operations["session_driver_profile_api_sessions__session_id__driver_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/frames": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Frames */
        get: operations["session_frames_api_sessions__session_id__frames_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Settings */
        patch: operations["patch_settings_api_settings_patch"];
        trace?: never;
    };
    "/api/track/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Track Current
         * @description API spec §8 `GET /api/track/current`. Always returns
         *     `inferred=true` in MVP (FR-019).
         */
        get: operations["track_current_api_track_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/track/mistakes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mistakes
         * @description T078: aggregated mistake heatmap. MVP returns the documented
         *     shape with zero buckets until detectors persist mistakes (lands with
         *     coach detectors in US3 / event detectors in US1).
         */
        get: operations["mistakes_api_track_mistakes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/track/optimal-line": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Optimal Line
         * @description T077: AI-computed optimal line vs. driver's line.
         *
         *     MVP returns the recorded line on both sides (your-line == optimal-line)
         *     and an empty incidents list. Full optimal-line synthesis lands when
         *     the lap-residual + corner-detection models stabilise (US5/US6).
         */
        get: operations["optimal_line_api_track_optimal_line_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Telemetry Health */
        get: operations["get_telemetry_health_health_telemetry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BestAchievableLapResponse */
        BestAchievableLapResponse: {
            /** Confidence */
            confidence: number;
            /** Inputs */
            inputs: string[];
            /**
             * Kind
             * @default bestAchievableLap
             * @constant
             */
            kind: "bestAchievableLap";
            /** Modelversion */
            modelVersion: string;
            /** Toleranceband */
            toleranceBand: number;
            /** Value */
            value: number;
        };
        /** CalloutSummary */
        CalloutSummary: {
            /** Ats */
            atS: number;
            /** Id */
            id: string;
            /**
             * Priority
             * @enum {string}
             */
            priority: "tip" | "info" | "warn";
            /** Text */
            text: string;
        };
        /** CarAggregateResponse */
        CarAggregateResponse: {
            /** Carid */
            carId: string;
            /**
             * Gripbudgetceiling
             * @default 0
             */
            gripBudgetCeiling: number;
            /**
             * Lapstotal
             * @default 0
             */
            lapsTotal: number;
            /** Percorneraverages */
            perCornerAverages?: components["schemas"]["PerCornerAverage"][];
            /** Preferredgearbycorner */
            preferredGearByCorner?: components["schemas"]["PreferredGearByCorner"][];
            /** Sectorbests */
            sectorBests?: components["schemas"]["SectorBest"][];
            /** Shift */
            shift?: {
                [key: string]: number;
            };
            /** Thiscarspecificstyle */
            thisCarSpecificStyle?: {
                [key: string]: number;
            };
            /** Tirepeakusebycorner */
            tirePeakUseByCorner?: components["schemas"]["TirePeakByCorner"][];
        };
        /** CarBestLap */
        CarBestLap: {
            /** Bestlaps */
            bestLapS: number;
            /** Trackid */
            trackId: string;
        };
        /** CarListResponse */
        CarListResponse: {
            /** Cars */
            cars: components["schemas"]["CarSummary"][];
        };
        /** CarRenameRequest */
        CarRenameRequest: {
            /** Displayname */
            displayName: string;
        };
        /** CarRenameResponse */
        CarRenameResponse: {
            /** Displayname */
            displayName: string;
            /** Ordinal */
            ordinal: number;
            /** Shortname */
            shortName: string;
            /** Updated */
            updated: number;
        };
        /** CarSummary */
        CarSummary: {
            /** Bestlapbytrack */
            bestLapByTrack?: components["schemas"]["CarBestLap"][];
            /** Class */
            class: string;
            /** Display */
            display: string;
            /**
             * Drivetrain
             * @enum {string}
             */
            drivetrain: "FWD" | "RWD" | "AWD";
            /** Group */
            group: number;
            /** Grouplabel */
            groupLabel?: string | null;
            /** Id */
            id: string;
            /** Lastseenat */
            lastSeenAt?: string | null;
            /** Ordinal */
            ordinal: number;
            /** Pi */
            pi: number;
            /**
             * Sessioncount
             * @default 0
             */
            sessionCount: number;
            /** Short */
            short: string;
            /**
             * Totalsecondsdriven
             * @default 0
             */
            totalSecondsDriven: number;
        };
        /** CoachAskRequest */
        CoachAskRequest: {
            /** Question */
            question: string;
            /** Sessionid */
            sessionId: string;
        };
        /** CoachStatus */
        CoachStatus: {
            /** Available */
            available: boolean;
            /** Model */
            model?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /** CornerStat */
        CornerStat: {
            /** Avgapexspeedmps */
            avgApexSpeedMps: number;
            /** Avgentryspeedmps */
            avgEntrySpeedMps: number;
            /** Avgexitspeedmps */
            avgExitSpeedMps: number;
            /** Corner */
            corner: string;
        };
        /** CrashRiskPredictionResponse */
        CrashRiskPredictionResponse: {
            /** Confidence */
            confidence: number;
            /** Inputs */
            inputs: string[];
            /**
             * Kind
             * @default crashRisk
             * @constant
             */
            kind: "crashRisk";
            /** Modelversion */
            modelVersion: string;
            /** Toleranceband */
            toleranceBand: number;
            /** Value */
            value: number;
        };
        /** DataSettings */
        DataSettings: {
            /**
             * Maxbytespercar
             * @default 5368709120
             */
            maxBytesPerCar: number;
            /**
             * Recordsessions
             * @default true
             */
            recordSessions: boolean;
            /**
             * Retentiondays
             * @default 90
             */
            retentionDays: number;
            /**
             * Shareanalytics
             * @default false
             */
            shareAnalytics: boolean;
            /**
             * Storerawpackets
             * @default false
             */
            storeRawPackets: boolean;
        };
        /** DisplaySettings */
        DisplaySettings: {
            /**
             * Reducemotion
             * @default false
             */
            reduceMotion: boolean;
            /**
             * Speedunit
             * @default kmh
             * @enum {string}
             */
            speedUnit: "kmh" | "mph";
            /**
             * Tempunit
             * @default c
             * @enum {string}
             */
            tempUnit: "f" | "c";
            /**
             * Theme
             * @default dark
             * @enum {string}
             */
            theme: "dark" | "light";
        };
        /** DriverEvolutionResponse */
        DriverEvolutionResponse: {
            /** Days */
            days: number;
            /** Series */
            series: {
                [key: string]: number[][];
            };
            /** Sessionclusters */
            sessionClusters?: components["schemas"]["SessionClusterPoint"][];
        };
        /** DriverProfileResponse */
        DriverProfileResponse: {
            /** Caragnosticshare */
            carAgnosticShare: number;
            /** Distanceanalyzedm */
            distanceAnalyzedM: number;
            /** Fingerprint */
            fingerprint: {
                [key: string]: number;
            };
            /** Fingerprintbaseline90D */
            fingerprintBaseline90d: {
                [key: string]: number;
            };
            /** Lapsanalyzed */
            lapsAnalyzed: number;
            /** Modelversion */
            modelVersion: string;
            /** Persona */
            persona: string;
            /** Personaupdatedat */
            personaUpdatedAt?: string | null;
            /** Secondsanalyzed */
            secondsAnalyzed: number;
            /** Strengths */
            strengths: string[];
            /** Traits */
            traits: components["schemas"]["DriverTrait"][];
            /** Weaknesses */
            weaknesses: string[];
        };
        /** DriverTrait */
        DriverTrait: {
            /** Blurb */
            blurb: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Score */
            score: number;
        };
        /** Fingerprint */
        Fingerprint: {
            /** Carordinal */
            carOrdinal: number | null;
            /** Numcylinders */
            numCylinders: number | null;
            /** Performanceindex */
            performanceIndex: number | null;
        };
        /** FinishPredictionResponse */
        FinishPredictionResponse: {
            /** Confidence */
            confidence: number;
            /** Inputs */
            inputs: string[];
            /**
             * Kind
             * @default finish
             * @constant
             */
            kind: "finish";
            /** Modelversion */
            modelVersion: string;
            /** Toleranceband */
            toleranceBand: number;
            /** Value */
            value: number;
        };
        /** GridConfig */
        GridConfig: {
            /**
             * Cols
             * @default 12
             */
            cols: number;
            /**
             * Rowheight
             * @default 40
             */
            rowHeight: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IncidentMark */
        IncidentMark: {
            /** Ats */
            atS: number;
            /** Kind */
            kind: string;
            /** Text */
            text?: string | null;
        };
        /** InsightCard */
        InsightCard: {
            /** Actions */
            actions?: string[];
            /** Body */
            body: string;
            /** Deltaiffixeds */
            deltaIfFixedS?: number | null;
            /** Id */
            id: string;
            /**
             * Priority
             * @enum {string}
             */
            priority: "high" | "medium" | "low";
            /** Replayid */
            replayId?: string | null;
            /** Sessionid */
            sessionId: string;
            /** Title */
            title: string;
            /**
             * Tone
             * @default tip
             * @enum {string}
             */
            tone: "tip" | "info" | "warn";
        };
        /** InsightsResponse */
        InsightsResponse: {
            /** Insights */
            insights: components["schemas"]["InsightCard"][];
        };
        /**
         * LapPrediction
         * @description One projected lap with its own confidence band (api-contract §6).
         */
        LapPrediction: {
            /** Confidence */
            confidence: number;
            /** Lap */
            lap: number;
            /** Lower S */
            lower_s: number;
            /** Time S */
            time_s: number;
            /** Upper S */
            upper_s: number;
        };
        /**
         * LapPredictionResponse
         * @description Multi-lap projection response (api-contract §6).
         *
         *     Replaces the legacy `PredictionEnvelope`-based single-value shape; the
         *     handler still emits the old shape until Task 1C.2 rewires it.
         */
        LapPredictionResponse: {
            /** Inputs */
            inputs: string[];
            /** Limiter */
            limiter?: string | null;
            /** Modelversion */
            modelVersion: string;
            /** Predictedat */
            predictedAt: number;
            /** Predictions */
            predictions: components["schemas"]["LapPrediction"][];
        };
        /** LapRollup */
        LapRollup: {
            /**
             * Avgbrake
             * @default 0
             */
            avgBrake: number;
            /**
             * Avgthrottle
             * @default 0
             */
            avgThrottle: number;
            /** Lap */
            lap: number;
            /** Sectortimes */
            sectorTimes?: number[];
            /** Times */
            timeS: number | null;
            /**
             * Topspeedmps
             * @default 0
             */
            topSpeedMps: number;
        };
        /** LayoutPatchBody */
        LayoutPatchBody: {
            grid?: components["schemas"]["GridConfig"] | null;
            /** Name */
            name?: string | null;
            /** Widgets */
            widgets?: components["schemas"]["WidgetInstance"][] | null;
        };
        /** LayoutPutBody */
        LayoutPutBody: {
            grid?: components["schemas"]["GridConfig"];
            /**
             * Name
             * @default
             */
            name: string;
            /** Widgets */
            widgets: components["schemas"]["WidgetInstance"][];
        };
        /** LayoutResponse */
        LayoutResponse: {
            grid?: components["schemas"]["GridConfig"];
            /**
             * Name
             * @default
             */
            name: string;
            /** Pageid */
            pageId: string;
            /** Updatedat */
            updatedAt?: string | null;
            /** Widgets */
            widgets?: components["schemas"]["WidgetInstance"][];
        };
        /** MistakeBreakdown */
        MistakeBreakdown: {
            /** Count */
            count: number;
            /** Kind */
            kind: string;
        };
        /** MistakeBucket */
        MistakeBucket: {
            /** Corner */
            corner?: string | null;
            /** Count */
            count: number;
            /** Kind */
            kind: string;
            /** Pos */
            pos: number[];
        };
        /** MistakeTrendPoint */
        MistakeTrendPoint: {
            /** Count */
            count: number;
            /** Dayiso */
            dayIso: string;
        };
        /** MistakesHeatmapResponse */
        MistakesHeatmapResponse: {
            /** Breakdown */
            breakdown?: components["schemas"]["MistakeBreakdown"][];
            /** Buckets */
            buckets?: components["schemas"]["MistakeBucket"][];
            /** Carid */
            carId: string;
            /** Trackid */
            trackId: string | null;
            /** Trend */
            trend?: components["schemas"]["MistakeTrendPoint"][];
        };
        /** ModelsSettings */
        ModelsSettings: {
            /**
             * Drivingfingerprint
             * @default true
             */
            drivingFingerprint: boolean;
            /**
             * Llmcoach
             * @default true
             */
            llmCoach: boolean;
            /**
             * Mincoachpriority
             * @default tip
             * @enum {string}
             */
            minCoachPriority: "info" | "tip" | "warn";
            /**
             * Predictions
             * @default true
             */
            predictions: boolean;
            /**
             * Shiftcoach
             * @default true
             */
            shiftCoach: boolean;
            /**
             * Tirewearmodel
             * @default true
             */
            tireWearModel: boolean;
            /**
             * Voicecallouts
             * @default false
             */
            voiceCallouts: boolean;
        };
        /** OptimalLinePoint */
        OptimalLinePoint: {
            /** Brake */
            brake: number;
            /** Speed */
            speed: number;
            /** T */
            t: number;
            /** Throttle */
            throttle: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** OptimalLineResponse */
        OptimalLineResponse: {
            /** Incidents */
            incidents?: components["schemas"]["IncidentMark"][];
            /** Optimalline */
            optimalLine?: components["schemas"]["OptimalLinePoint"][];
            /** Sectordeltas */
            sectorDeltas?: components["schemas"]["SectorDelta"][];
            /** Sessionid */
            sessionId: string;
            /** Trackid */
            trackId: string;
            /** Yourline */
            yourLine?: components["schemas"]["OptimalLinePoint"][];
        };
        /** PerCarOverride */
        PerCarOverride: {
            /** Carid */
            carId: string;
            /** Layoutid */
            layoutId?: string | null;
            /** Presetid */
            presetId?: string | null;
        };
        /** PerCornerAverage */
        PerCornerAverage: {
            /** Avgapexspeedmps */
            avgApexSpeedMps: number;
            /** Avgentryspeedmps */
            avgEntrySpeedMps: number;
            /** Avgexitspeedmps */
            avgExitSpeedMps: number;
            /** Corner */
            corner: string;
        };
        /** PreferredGearByCorner */
        PreferredGearByCorner: {
            /** Corner */
            corner: string;
            /** Gear */
            gear: number;
        };
        /** ReplayResponse */
        ReplayResponse: {
            /** Annotations */
            annotations?: {
                [key: string]: unknown;
            }[];
            /** Createdat */
            createdAt?: string | null;
            /** Frames */
            frames?: unknown[][];
            /** From */
            from: number;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "counter_factual" | "telemetry_clip";
            /** Sessionid */
            sessionId: string;
            /** To */
            to: number;
            /** Tweaks */
            tweaks?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** SectorBest */
        SectorBest: {
            /** Bests */
            bestS: number;
            /** Sector */
            sector: number;
        };
        /** SectorDelta */
        SectorDelta: {
            /** Deltas */
            deltaS: number;
            /** Sector */
            sector: number;
        };
        /** SessionClusterPoint */
        SessionClusterPoint: {
            /** Fingerprint */
            fingerprint: {
                [key: string]: number;
            };
            /** Sessionid */
            sessionId: string;
        };
        /** SessionDetailResponse */
        SessionDetailResponse: {
            /** Bestlaps */
            bestLapS?: number | null;
            /**
             * Bookmarked
             * @default false
             */
            bookmarked: boolean;
            /** Callouts */
            callouts?: components["schemas"]["CalloutSummary"][];
            /** Carid */
            carId: string;
            /** Closedreason */
            closedReason?: string | null;
            /**
             * Distancem
             * @default 0
             */
            distanceM: number;
            /** Durations */
            durationS?: number | null;
            /** Endedat */
            endedAt?: string | null;
            /** Events */
            events?: components["schemas"]["SessionEventEntry"][];
            /** Id */
            id: string;
            /**
             * Lapcount
             * @default 0
             */
            lapCount: number;
            /** Laprollups */
            lapRollups?: components["schemas"]["LapRollup"][];
            /** Name */
            name?: string | null;
            /** Percornerstats */
            perCornerStats?: components["schemas"]["CornerStat"][];
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            /** Styledriftdelta */
            styleDriftDelta?: {
                [key: string]: number;
            };
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Timeline10Hz */
            timeline10hz?: components["schemas"]["TimelinePoint"][];
            /**
             * Topspeedmps
             * @default 0
             */
            topSpeedMps: number;
            /** Trackid */
            trackId?: string | null;
            /** Type */
            type: string;
        };
        /**
         * SessionEventEntry
         * @description One row from the historical session_events log.
         *
         *     Drives the highlight-reel / chronological event widget on the
         *     session-detail page. `atS` is seconds since `startedAt`.
         */
        SessionEventEntry: {
            /** Ats */
            atS: number;
            /** Kind */
            kind: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
        };
        /** SessionFramesResponse */
        SessionFramesResponse: {
            /** Data */
            data: unknown[][];
            /** Fields */
            fields: string[];
            /**
             * Hz
             * @enum {integer}
             */
            hz: 10 | 30 | 60;
            /** Sessionid */
            sessionId: string;
        };
        /** SessionListItem */
        SessionListItem: {
            /** Bestlaps */
            bestLapS?: number | null;
            /**
             * Bookmarked
             * @default false
             */
            bookmarked: boolean;
            /** Carid */
            carId: string;
            /** Closedreason */
            closedReason?: string | null;
            /**
             * Distancem
             * @default 0
             */
            distanceM: number;
            /** Durations */
            durationS?: number | null;
            /** Endedat */
            endedAt?: string | null;
            /** Id */
            id: string;
            /**
             * Lapcount
             * @default 0
             */
            lapCount: number;
            /** Name */
            name?: string | null;
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Topspeedmps
             * @default 0
             */
            topSpeedMps: number;
            /** Trackid */
            trackId?: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "free_roam" | "race" | "time_trial" | "drift" | "cross_country";
        };
        /** SessionPatchRequest */
        SessionPatchRequest: {
            /** Bookmarked */
            bookmarked?: boolean | null;
            /** Name */
            name?: string | null;
        };
        /**
         * SettingsPatch
         * @description Partial — any subset of the top-level keys.
         */
        SettingsPatch: {
            data?: components["schemas"]["DataSettings"] | null;
            display?: components["schemas"]["DisplaySettings"] | null;
            models?: components["schemas"]["ModelsSettings"] | null;
            /** Percaroverrides */
            perCarOverrides?: components["schemas"]["PerCarOverride"][] | null;
            telemetry?: components["schemas"]["TelemetrySettings"] | null;
            worldMap?: components["schemas"]["WorldMapSettings"] | null;
        };
        /** SettingsResponse */
        SettingsResponse: {
            data: components["schemas"]["DataSettings"];
            display: components["schemas"]["DisplaySettings"];
            models: components["schemas"]["ModelsSettings"];
            /** Percaroverrides */
            perCarOverrides?: components["schemas"]["PerCarOverride"][];
            telemetry: components["schemas"]["TelemetrySettings"];
            worldMap?: components["schemas"]["WorldMapSettings"];
        };
        /**
         * ShiftPredictResponse
         * @description Response shape for GET /api/predict/shift (FR-021).
         */
        ShiftPredictResponse: {
            /** Bygear */
            byGear: {
                [key: string]: number;
            };
            /** Confidence */
            confidence: number;
            /** Confidencebygear */
            confidenceByGear: {
                [key: string]: number;
            };
            fingerprint: components["schemas"]["Fingerprint"];
            /** Inputs */
            inputs: string[];
            /** Lastupdated */
            lastUpdated: string | null;
            /** Modelversion */
            modelVersion: string;
            /** Ratioconfidencebygear */
            ratioConfidenceByGear: {
                [key: string]: number;
            };
            /** Ratios */
            ratios: {
                [key: string]: number;
            };
            /** Stage */
            stage: string;
            /** Trainedsamplecount */
            trainedSampleCount: number;
        };
        /** ShiftReportPairAgg */
        ShiftReportPairAgg: {
            /** Avgdeltarpm */
            avgDeltaRpm: number;
            /** Avgestcosts */
            avgEstCostS: number;
            /**
             * Direction
             * @enum {string}
             */
            direction: "up" | "down";
            /** N */
            n: number;
        };
        /**
         * ShiftReportResponse
         * @description Response shape for GET /api/predict/shift/report (FR-022, FR-051).
         *
         *     v2 additions (FR-051):
         *     - ``assistInterventionPct``: session-lifetime assist-intervention fraction in
         *       [0, 1].  Sourced from the live ``ShiftPredictor``'s in-memory session
         *       counters when ``sessionId=live``; 0.0 for historical sessions because the
         *       assist counter is not persisted between process restarts.
         *     - ``byGearPair[*].direction``: "up" for gear_to > gear_from, "down" otherwise.
         */
        ShiftReportResponse: {
            /** Assistinterventionpct */
            assistInterventionPct: number;
            /** Avgdeltarpm */
            avgDeltaRpm: number;
            /** Bygearpair */
            byGearPair: {
                [key: string]: components["schemas"]["ShiftReportPairAgg"];
            };
            /** Cleanshifts */
            cleanShifts: number;
            /** Esttotalcosts */
            estTotalCostS: number;
            /** Modelversion */
            modelVersion: string;
            /** Sessionid */
            sessionId: string;
            /** Totalshifts */
            totalShifts: number;
        };
        /** ShiftResetCounts */
        ShiftResetCounts: {
            /** Enginecurves */
            engineCurves: number;
            /** Gearratios */
            gearRatios: number;
            /** Shiftevents */
            shiftEvents: number;
            /** Transmissionmodes */
            transmissionModes: number;
        };
        /**
         * ShiftResetRequest
         * @description POST /api/predict/shift/reset body (FR-023).
         *
         *     Accepts EITHER explicit (carOrdinal, performanceIndex, numCylinders)
         *     OR sessionId="live"/<id> to resolve the fingerprint from the live frame.
         */
        ShiftResetRequest: {
            /** Carordinal */
            carOrdinal?: number | null;
            /** Numcylinders */
            numCylinders?: number | null;
            /** Performanceindex */
            performanceIndex?: number | null;
            /** Sessionid */
            sessionId?: string | null;
        };
        /** ShiftResetResponse */
        ShiftResetResponse: {
            deleted: components["schemas"]["ShiftResetCounts"];
        };
        /** TelemetrySettings */
        TelemetrySettings: {
            /**
             * Autodetectcadence
             * @default true
             */
            autoDetectCadence: boolean;
            /**
             * Gameprofile
             * @default fh6
             * @constant
             */
            gameProfile: "fh6";
            /**
             * Listenaddr
             * @default 127.0.0.1
             */
            listenAddr: string;
            /**
             * Listenport
             * @default 5302
             */
            listenPort: number;
            /**
             * Preferredframerate
             * @default 30
             * @enum {integer}
             */
            preferredFrameRate: 10 | 30 | 60;
        };
        /** TimelinePoint */
        TimelinePoint: {
            /** Brake */
            brake: number | null;
            /** Speed */
            speed: number | null;
            /** T */
            t: number;
            /** Throttle */
            throttle: number | null;
        };
        /** TireFailurePerCorner */
        TireFailurePerCorner: {
            /** Confidence */
            confidence: number;
            /** Failureatlap */
            failureAtLap?: number | null;
            /** Wear */
            wear: number;
        };
        /**
         * TireFailurePredictionResponse
         * @description Per-corner tire-failure projection.
         *
         *     `perCorner` maps each wheel (fl, fr, rl, rr) to its current wear,
         *     a projected lap when wear hits 1.0 (None for free-roam / cold
         *     session), and the model's confidence. `limitingCorner` is the
         *     wheel with the earliest projected failure (or the highest wear if
         *     no laps yet).
         */
        TireFailurePredictionResponse: {
            /** Inputs */
            inputs: string[];
            /** Limitingcorner */
            limitingCorner?: string | null;
            /** Modelversion */
            modelVersion: string;
            /** Percorner */
            perCorner: {
                [key: string]: components["schemas"]["TireFailurePerCorner"];
            };
        };
        /** TirePeakByCorner */
        TirePeakByCorner: {
            /** Corner */
            corner: string;
            /** Peaktemp */
            peakTemp: number;
        };
        /** TrackCurrentResponse */
        TrackCurrentResponse: {
            /** Confirmedat */
            confirmedAt?: string | null;
            /** Confirmedname */
            confirmedName?: string | null;
            /** Corners */
            corners?: {
                [key: string]: unknown;
            }[];
            /** Displayname */
            displayName: string;
            /**
             * Inferred
             * @default true
             */
            inferred: boolean;
            /** Outline */
            outline?: number[][];
            /** Trackid */
            trackId: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WhatIfPerTweak */
        WhatIfPerTweak: {
            /** Deltas */
            deltaS: number;
            /** Kind */
            kind: string;
        };
        /** WhatIfRequest */
        WhatIfRequest: {
            /**
             * From
             * @default 0
             */
            from: number;
            /** Sessionid */
            sessionId: string;
            /**
             * To
             * @default 60
             */
            to: number;
            /** Tweaks */
            tweaks: components["schemas"]["WhatIfTweak"][];
        };
        /** WhatIfResponse */
        WhatIfResponse: {
            /** Confidence */
            confidence: number;
            /** Lapdeltas */
            lapDeltaS: number;
            /** Modelversion */
            modelVersion: string;
            /** Pertweak */
            perTweak: components["schemas"]["WhatIfPerTweak"][];
            /** Replayid */
            replayId: string;
            /** Sessionid */
            sessionId: string;
            /** Toleranceband */
            toleranceBand: number;
        };
        /** WhatIfTweak */
        WhatIfTweak: {
            /** Delta */
            delta: number;
            /** Kind */
            kind: string;
        };
        /** WidgetInstance */
        WidgetInstance: {
            /** H */
            h: number;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Props */
            props?: {
                [key: string]: unknown;
            };
            /** W */
            w: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * WorldMapCalibration
         * @description Two reference points mapping FH6 world (X, Z) → tile-pyramid pixel (X, Y).
         *
         *     Stored as lists for JSON round-trip stability. The widget derives a per-axis
         *     linear transform from these four pairs; see api-contract §10 + the world_map
         *     widget for the math.
         */
        WorldMapCalibration: {
            /** Apix */
            aPix: number[];
            /** Aworld */
            aWorld: number[];
            /** Bpix */
            bPix: number[];
            /** Bworld */
            bWorld: number[];
        };
        /**
         * WorldMapSettings
         * @description Configuration for the `world_map` widget.
         *
         *     `calibration` is null until the user runs the in-widget calibration tool
         *     (capture point A's world coords from telemetry, click pixel A on the map,
         *     repeat for B). Defaults to the fh6-tel Japan preset so the widget renders
         *     correctly against the bundled tile pyramid before users run their own
         *     calibration on the real FH6 map.
         */
        WorldMapSettings: {
            calibration?: components["schemas"]["WorldMapCalibration"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_cars_api_cars_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarListResponse"];
                };
            };
        };
    };
    delete_car_api_cars__car_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                car_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    car_aggregate_api_cars__car_id__aggregate_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                car_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarAggregateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_car_sessions_api_cars__car_id__sessions_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                car_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_car_by_ordinal_api_cars__ordinal__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ordinal: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarRenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarRenameResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_api_coach_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoachAskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_insights_api_coach_insights_get: {
        parameters: {
            query: {
                sessionId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_insight_api_coach_insights__insight_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                insight_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_insight_api_coach_insights__insight_id__replay_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                insight_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_for_session_api_coach_insights__session_id__generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coach_status_api_coach_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachStatus"];
                };
            };
        };
    };
    delete_all_data_api_data_all_delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Confirm"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evolution_api_driver_evolution_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverEvolutionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_api_driver_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverProfileResponse"];
                };
            };
        };
    };
    get_layout_api_layouts__page_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_layout_api_layouts__page_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayoutPutBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_layout_api_layouts__page_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayoutPatchBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    best_achievable_lap_api_predict_bestAchievableLap_get: {
        parameters: {
            query: {
                sessionId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BestAchievableLapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crash_risk_api_predict_crashRisk_get: {
        parameters: {
            query: {
                sessionId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrashRiskPredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finish_api_predict_finish_get: {
        parameters: {
            query: {
                sessionId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinishPredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lap_api_predict_lap_get: {
        parameters: {
            query: {
                sessionId: string;
                n?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LapPredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shift_prediction_api_predict_shift_get: {
        parameters: {
            query: {
                sessionId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftPredictResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shift_report_api_predict_shift_report_get: {
        parameters: {
            query: {
                sessionId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_shift_reset_api_predict_shift_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShiftResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftResetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tire_failure_api_predict_tireFailure_get: {
        parameters: {
            query: {
                sessionId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TireFailurePredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    what_if_api_predict_whatIf_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhatIfRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatIfResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_replay_api_replay__replay_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                replay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: {
                carId?: string | null;
                type?: string | null;
                from?: string | null;
                to?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_all_sessions_api_sessions_delete: {
        parameters: {
            query?: never;
            header?: {
                "x-confirm-clear-all"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_session_api_sessions_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListItem"];
                };
            };
        };
    };
    session_detail_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_session_api_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_driver_profile_api_sessions__session_id__driver_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_frames_api_sessions__session_id__frames_get: {
        parameters: {
            query?: {
                hz?: number;
                fields?: string | null;
                from?: number | null;
                to?: number | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionFramesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    patch_settings_api_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    track_current_api_track_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackCurrentResponse"];
                };
            };
        };
    };
    mistakes_api_track_mistakes_get: {
        parameters: {
            query: {
                carId: string;
                trackId?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MistakesHeatmapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimal_line_api_track_optimal_line_get: {
        parameters: {
            query: {
                sessionId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimalLineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_telemetry_health_health_telemetry_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
