/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Fields = string[] | null;
export type From = string | null;
export type Kind = "telemetry_window" | "lap_aggregate";
export type Sector = number | null;
export type Sessionid = string;
export type To = string | null;
export type Hz = 10 | 30 | 60;
export type Type = "rate";
export type Topics = ("frames" | "events" | "coach")[];
export type Type1 = "subscribe";
export type Available = boolean;
export type Model = string | null;
export type Reason = string | null;
export type Server = string;
export type Type2 = "hello";
export type Ats = number;
export type Cites = Citation[];
export type Corner = string;
export type Id = string;
export type Lap = number;
export type Modelversion = string;
export type Priority = "tip" | "info" | "warn";
export type Text = string;
export type Type3 = "callout";
export type Voice = string;
export type Balance = number;
export type Bodycontrol = number;
export type Gripbudgetused = number;
export type Powerbandoccupancy = number;
export type StopdistanceM = number;
export type Throttlesmoothness = number;
export type Weightfront = number;
export type Weightleft = number;
export type Clutch = number;
export type Gear = number;
export type Type4 = string;
export type BoostPsi = number;
export type Fuel = number;
export type Idlerpm = number;
export type Maxrpm = number;
export type PowerW = number;
export type Rpm = number;
export type TorqueNm = number;
export type At = number | null;
export type Kind1 = string;
export type Type5 = "event";
export type Carid = string;
export type Aibrakedelta = number;
export type Brake = number;
export type Clutch1 = number;
export type Drivingline = number;
export type Handbrake = number;
export type Steer = number;
export type Throttle = number;
export type Israceon = boolean;
export type Modeledbyversion = string;
export type Currentgearconfidence = number;
export type Currentgeartarget = number | null;
export type Displayactive = boolean;
export type Modelversion1 = string;
export type Stage = "learned" | "prior" | "fallback";
export type Fl = number;
export type Fr = number;
export type Rl = number;
export type Rr = number;
export type Tirewearconfidence = number;
export type X = number;
export type Y = number;
export type Z = number;
export type Pitch = number;
export type Roll = number;
export type Yaw = number;
export type SpeedMps = number;
export type Bestlaps = number | null;
export type Currentlaps = number | null;
export type Lap1 = number;
export type Lastlaps = number | null;
export type Position = number;
export type Racetimes = number;
export type Sessionid1 = string;
export type T = number;
export type Type6 = "frame";
export type Combinedslip = number;
export type Inpuddle = number;
export type Onrumble = number;
export type RotationRadS = number;
export type Slipangle = number;
export type Slipratio = number;
export type Surfacerumble = number;
export type SuspensiontravelM = number;
export type SuspensiontravelNorm = number;
export type TiretempC = number;
export type TiretempNormwindow = number;
export type Carclass = string;
export type Cargroup = number;
export type Carordinal = number;
export type Numcylinders = number;
export type Performanceindex = number;
export type Smashablemass = number;
export type Smashableveldiff = number;
export type Batch = Frame[];
export type Type7 = "frames";
export type At1 = number;
export type Type8 = "heartbeat";
export type Capabilities = string[];
export type Server1 = string;
export type Type9 = "hello";
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "LiveInbound".
 */
export type LiveInbound = ClientSubscribe | ClientRateChange;
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "LiveOutbound".
 */
export type LiveOutbound = Frame | FrameBatch | StateMessage | EventMessage | Heartbeat | Hello;
export type At2 = number;
export type Lastframeat = number | null;
export type Reason1 = string | null;
export type State = "driving" | "stream-paused" | "stream-resumed" | "stream-lost";
export type Type10 = "state";

export interface FhRacerWebSocketMessageSchemas {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "Citation".
 */
export interface Citation {
  fields?: Fields;
  from?: From;
  kind: Kind;
  sector?: Sector;
  sessionId: Sessionid;
  to?: To;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "ClientRateChange".
 */
export interface ClientRateChange {
  hz: Hz;
  type?: Type;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "ClientSubscribe".
 */
export interface ClientSubscribe {
  topics: Topics;
  type?: Type1;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "CoachHello".
 */
export interface CoachHello {
  coach: CoachStatus;
  server: Server;
  type?: Type2;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "CoachStatus".
 */
export interface CoachStatus {
  available: Available;
  model?: Model;
  reason?: Reason;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "CoachOutbound".
 */
export interface CalloutMessage {
  atS: Ats;
  cites?: Cites;
  corner: Corner;
  id: Id;
  lap: Lap;
  modelVersion?: Modelversion;
  priority: Priority;
  text: Text;
  type?: Type3;
  voice?: Voice;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "DerivedBlock".
 */
export interface DerivedBlock {
  balance: Balance;
  bodyControl: Bodycontrol;
  gripBudgetUsed: Gripbudgetused;
  powerBandOccupancy: Powerbandoccupancy;
  stopDistance_m?: StopdistanceM;
  throttleSmoothness: Throttlesmoothness;
  weightFront: Weightfront;
  weightLeft: Weightleft;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "DrivetrainBlock".
 */
export interface DrivetrainBlock {
  clutch: Clutch;
  gear: Gear;
  type: Type4;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "EngineBlock".
 */
export interface EngineBlock {
  boost_psi: BoostPsi;
  fuel: Fuel;
  idleRpm: Idlerpm;
  maxRpm: Maxrpm;
  power_w: PowerW;
  rpm: Rpm;
  torque_nm: TorqueNm;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "EventMessage".
 */
export interface EventMessage {
  at?: At;
  kind: Kind1;
  type?: Type5;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "Frame".
 */
export interface Frame {
  carId: Carid;
  derived: DerivedBlock;
  drivetrain: DrivetrainBlock;
  engine: EngineBlock;
  inputs: InputsBlock;
  isRaceOn: Israceon;
  modeled: ModeledBlock;
  motion: MotionBlock;
  race: RaceBlock;
  sessionId: Sessionid1;
  t: T;
  type?: Type6;
  wheels: WheelsBlock;
  world: WorldBlock;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "InputsBlock".
 */
export interface InputsBlock {
  aiBrakeDelta: Aibrakedelta;
  brake: Brake;
  clutch: Clutch1;
  drivingLine: Drivingline;
  handbrake: Handbrake;
  steer: Steer;
  throttle: Throttle;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "ModeledBlock".
 */
export interface ModeledBlock {
  modeledByVersion: Modeledbyversion;
  shiftRecommendation?: ShiftRecommendation | null;
  tireWear: ModeledTireWear;
  tireWearConfidence: Tirewearconfidence;
}
/**
 * Per-frame projection of the learned shift recommendation (FR-018).
 *
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "ShiftRecommendation".
 */
export interface ShiftRecommendation {
  byGear: Bygear;
  byGearSamples: Bygearsamples;
  confidenceByGear: Confidencebygear;
  currentGearConfidence: Currentgearconfidence;
  currentGearTarget: Currentgeartarget;
  displayActive: Displayactive;
  fingerprint: Fingerprint;
  modelVersion: Modelversion1;
  stage: Stage;
}
export interface Bygear {
  [k: string]: number;
}
export interface Bygearsamples {
  [k: string]: number;
}
export interface Confidencebygear {
  [k: string]: number;
}
export interface Fingerprint {
  [k: string]: number | null;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "ModeledTireWear".
 */
export interface ModeledTireWear {
  fl: Fl;
  fr: Fr;
  rl: Rl;
  rr: Rr;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "MotionBlock".
 */
export interface MotionBlock {
  acceleration: Vec3;
  angularVelocity: Vec3;
  orientation: Orientation;
  position: Vec3;
  speed_mps: SpeedMps;
  velocity: Vec3;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "Vec3".
 */
export interface Vec3 {
  x: X;
  y: Y;
  z: Z;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "Orientation".
 */
export interface Orientation {
  pitch: Pitch;
  roll: Roll;
  yaw: Yaw;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "RaceBlock".
 */
export interface RaceBlock {
  bestLapS: Bestlaps;
  currentLapS: Currentlaps;
  lap: Lap1;
  lastLapS: Lastlaps;
  position: Position;
  raceTimeS: Racetimes;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "WheelsBlock".
 */
export interface WheelsBlock {
  fl: WheelBlock;
  fr: WheelBlock;
  rl: WheelBlock;
  rr: WheelBlock;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "WheelBlock".
 */
export interface WheelBlock {
  combinedSlip: Combinedslip;
  inPuddle: Inpuddle;
  onRumble: Onrumble;
  rotation_rad_s: RotationRadS;
  slipAngle: Slipangle;
  slipRatio: Slipratio;
  surfaceRumble: Surfacerumble;
  suspensionTravel_m: SuspensiontravelM;
  suspensionTravel_norm: SuspensiontravelNorm;
  tireTemp_c: TiretempC;
  tireTemp_normWindow: TiretempNormwindow;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "WorldBlock".
 */
export interface WorldBlock {
  carClass: Carclass;
  carGroup: Cargroup;
  carOrdinal: Carordinal;
  numCylinders: Numcylinders;
  performanceIndex: Performanceindex;
  smashableMass: Smashablemass;
  smashableVelDiff: Smashableveldiff;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "FrameBatch".
 */
export interface FrameBatch {
  batch: Batch;
  type?: Type7;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "Heartbeat".
 */
export interface Heartbeat {
  at: At1;
  type?: Type8;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "Hello".
 */
export interface Hello {
  capabilities?: Capabilities;
  server: Server1;
  type?: Type9;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "LiveErrorMessage".
 */
export interface LiveErrorMessage {
  code: "wrong-channel" | "unknown-topic" | "unknown-message" | "unsupported-rate";
  hz?: number | null;
  message?: string;
  received?: string | null;
  topics?: string[];
  type: "error";
  [k: string]: unknown;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "StateMessage".
 */
export interface StateMessage {
  at: At2;
  lastFrameAt?: Lastframeat;
  reason?: Reason1;
  state: State;
  type?: Type10;
}
/**
 * This interface was referenced by `FhRacerWebSocketMessageSchemas`'s JSON-Schema
 * via the `definition` "UdpBindFailedMessage".
 */
export interface UdpBindFailedMessage {
  message: string;
  type: "udp_bind_failed";
}
